### ISSUE TITLE
unzip file exception

### ISSUE THREAD

**Issue by zhzpeng** [mockingbot/react-native-zip-archive#89] opened 2018-03-23 10:21 UTC
when file's name contains  chinese characters，unzip function catched exception (works on android)

**Comment by plrthink** [comment] 2018-03-25 12:30
could you try this https://github.com/plrthink/react-native-zip-archive-none-ASCII-path-name out, or provide a minimal example to reproduce this issue?

also duplicated with https://github.com/mockingbot/react-native-zip-archive/issues/82, I'm going to close this and please continue on that thread

**Closed by plrthink** 2018-03-25 12:30 UTC

**Comment by zhzpeng** [comment] 2018-03-26 01:11
I'm sorry to describe the question, I mean the child file's name contains chinese characters which in zip file. just like this 
![image](https://user-images.githubusercontent.com/13147702/37882404-a778c566-30d5-11e8-8dbf-8485ebcada34.png)

**Comment by plrthink** [comment] 2018-03-26 01:21
@zhzpeng ok, will try it ASAP

**Comment by plrthink** [comment] 2018-04-01 15:30
@zhzpeng tried with the situation you describe but still can't reproduce the error. Could you please provide a minimal app to demonstrate the problem? That would be helpful to track the issue.

**Comment by zhzpeng** [comment] 2018-04-02 01:37
I updated react-native-zip-archive to new version 2.2.2 and it is OK to unzip chinese characters file. The exception occurs in version 2.2.1

**Comment by plrthink** [comment] 2018-04-02 01:47
look like we have fixed that unexpectedly, also it's recommended to always use the latest version.
